"""
Django settings for business project.

Generated by 'django-admin startproject' using Django 3.1.
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from storages.backends.gcloud import GoogleCloudStorage
from google.oauth2 import service_account
from django.core.exceptions import ImproperlyConfigured
from django.core.files.storage import default_storage 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inasoma faili la .env kiotomatiki
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'salama-default-key-kama-env-haipo')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://fanyabiashara.com',
    'http://fanyabiashara.com',
    'https://google.com', 
    'https://fanyabiashara-behqabgwdsh8dvb8.centralus-01.azurewebsites.net'
]

# Application definition
INSTALLED_APPS = [
    'management.apps.ManagementConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'business.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'business.wsgi.application'


# Database Configuration (Salama na Inasoma kutoka .env)
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'biashara',
            'USER': 'postgres',
            'PASSWORD': '1152',
            'HOST': 'localhost'
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static & Media Files Configuration
if DEBUG:
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    GS_BUCKET_NAME = 'fbiashara'  
    
    key_path = os.path.join(BASE_DIR, 'secrets', 'gcp-storage.json')
    GS_CREDENTIALS = service_account.Credentials.from_service_account_file(key_path)

    DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
    STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

    GS_MEDIA_LOCATION = 'media'
    GS_STATIC_LOCATION = 'static'

    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/{GS_MEDIA_LOCATION}/'
    STATIC_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/{GS_STATIC_LOCATION}/'

    GS_DEFAULT_ACL = None  
    GS_QUERYSTRING_AUTH = False

    GCS_STORAGE_INSTANCE = GoogleCloudStorage(
        bucket_name=GS_BUCKET_NAME,
        credentials=GS_CREDENTIALS,
        location=GS_MEDIA_LOCATION
    )

# Google Cloud Vision Credentials
GCP_JSON_KEY_PATH = os.path.join(BASE_DIR, 'secrets', 'gcp-vision-key.json')
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = GCP_JSON_KEY_PATH


# EMAIL CONFIGURATION (Salama dhidi ya Wadukuzi)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.privateemail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Zinasomwa kwa siri kutoka kwenye mfumo/.env sasa
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = f'FanyaBiashara <{EMAIL_HOST_USER}>'


# Message Tags Configuration
from django.contrib.messages import constants as message_constants
MESSAGE_TAGS = {
    message_constants.DEBUG: 'debug',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}