# Generated by Django 3.1 on 2022-05-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interprisepermissions',
            old_name='manunuzi',
            new_name='manunuziii',
        ),
    ]
