# Generated by Django 3.1 on 2022-05-11 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20220511_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='manunuzi',
            name='By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprisepermissions'),
        ),
    ]
