# Generated by Django 3.1 on 2022-05-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_manunuzi_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagents',
            name='Interprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise'),
        ),
        migrations.AlterField(
            model_name='deliveryagents',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.workers'),
        ),
    ]
