# Generated by Django 3.1 on 2022-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20220511_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagents',
            name='Interprise',
        ),
        migrations.RemoveField(
            model_name='deliveryagents',
            name='agent',
        ),
        migrations.AddField(
            model_name='deliveryagents',
            name='isAgenti',
            field=models.BooleanField(default=False),
        ),
    ]
