# Generated by Django 3.1 on 2022-05-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20220511_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagents',
            name='isAgenti',
        ),
        migrations.AddField(
            model_name='deliveryagents',
            name='Interprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprise'),
        ),
        migrations.AddField(
            model_name='deliveryagents',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.workers'),
        ),
    ]
