# Generated by Django 3.1 on 2022-05-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20220511_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_customers',
            name='by',
        ),
    ]
