# Generated by Django 3.1 on 2022-05-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_user_customers_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_customers',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.userextend'),
        ),
    ]
