# Generated by Django 3.1 on 2022-05-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_user_customers_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stokadjustment',
            old_name='By',
            new_name='Na',
        ),
    ]
