# Generated by Django 3.1 on 2022-05-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20220511_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_customers',
            name='labour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprisepermissions'),
        ),
    ]
