# Generated by Django 3.1 on 2022-05-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20220517_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_customers',
            name='labour',
        ),
        migrations.AddField(
            model_name='mauzoni',
            name='labour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.workers'),
        ),
    ]
