# Generated by Django 3.1 on 2022-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20220517_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='confirm_return',
            field=models.BooleanField(default=False),
        ),
    ]
