# Generated by Django 3.1 on 2022-05-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_mauzoni_confirm_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='request_return',
            field=models.BooleanField(default=False),
        ),
    ]
