# Generated by Django 3.1 on 2022-05-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_mauzoni_request_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaa_stoku',
            name='service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidhaa_stoku',
            name='timely',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
