# Generated by Django 3.1 on 2022-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20220525_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhaa_stoku',
            name='timely',
            field=models.IntegerField(default=0),
        ),
    ]
