# Generated by Django 3.1 on 2022-05-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20220525_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='servFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mauzoni',
            name='servTo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='mauzoni',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
