# Generated by Django 3.1 on 2022-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20220526_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mauzoni',
            name='servFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mauzoni',
            name='servTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
