# Generated by Django 3.1 on 2022-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20220526_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
