# Generated by Django 3.1 on 2022-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_mauzoni_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mauzoni',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
