# Generated by Django 3.1 on 2022-06-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20220530_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzolist',
            name='serviceReturn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales_color',
            name='serviceReturn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales_size',
            name='serviceReturn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202206),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202206),
        ),
    ]
