# Generated by Django 3.1 on 2022-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20220604_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzolist',
            name='timely',
            field=models.IntegerField(default=1),
        ),
    ]
