# Generated by Django 3.1 on 2022-06-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_mauzolist_timely'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mauzolist',
            old_name='timely',
            new_name='saveT',
        ),
    ]
