# Generated by Django 3.1 on 2022-07-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20220608_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202207),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202207),
        ),
        migrations.CreateModel(
            name='ChangedServiceTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.mauzoni')),
            ],
        ),
        migrations.CreateModel(
            name='ChangedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.mauzoni')),
                ('to_serv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.changedserviceto')),
            ],
        ),
    ]
