# Generated by Django 3.1 on 2022-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_auto_20220701_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='Changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
