# Generated by Django 3.1 on 2022-07-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_mauzoni_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='change',
            field=models.BooleanField(default=False),
        ),
    ]
