# Generated by Django 3.1 on 2022-07-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_mauzoni_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
