# Generated by Django 3.1 on 2022-07-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_mauzoni_ignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedServiceFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.mauzoni')),
            ],
        ),
        migrations.AddField(
            model_name='changedservice',
            name='From',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.changedservicefrom'),
        ),
    ]
