# Generated by Django 3.1 on 2022-07-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20220704_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
