# Generated by Django 3.1 on 2022-07-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_interprise_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wateja',
            name='where',
        ),
        migrations.AddField(
            model_name='wateja',
            name='Interprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprise'),
        ),
        migrations.CreateModel(
            name='wateja_active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprise')),
            ],
        ),
        migrations.AddField(
            model_name='wateja',
            name='mteja',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.wateja_active'),
        ),
    ]
