# Generated by Django 3.1 on 2022-07-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20220715_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wateja',
            name='owner',
        ),
    ]
