# Generated by Django 3.1 on 2022-07-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_remove_wateja_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='confirmRec',
            field=models.BooleanField(default=False),
        ),
    ]
