# Generated by Django 3.1 on 2022-07-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_mauzoni_confirmrec'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekodimatumizi',
            name='adjst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.stokadjustment'),
        ),
    ]
