# Generated by Django 3.1 on 2022-07-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_rekodimatumizi_adjst'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='prodxn',
            field=models.BooleanField(default=False),
        ),
    ]
