# Generated by Django 3.1 on 2022-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_interprisepermissions_prodxn'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='hamisha',
            field=models.BooleanField(default=False),
        ),
    ]
