# Generated by Django 3.1 on 2022-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_interprisepermissions_hamisha'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokadjustment',
            name='others',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202208),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202208),
        ),
    ]
