# Generated by Django 3.1 on 2022-08-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_auto_20220801_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wekacash',
            name='maelezo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
