# Generated by Django 3.1 on 2022-08-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_auto_20220807_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRiport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.DateTimeField()),
                ('to', models.DateTimeField()),
                ('sales', models.BooleanField(default=False)),
                ('By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprisepermissions')),
            ],
        ),
    ]
