# Generated by Django 3.1 on 2022-08-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_savedriport'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedriport',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedriport',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
