# Generated by Django 3.1 on 2022-08-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_auto_20220809_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaa_stoku',
            name='full_Return',
            field=models.BooleanField(default=False),
        ),
    ]
