# Generated by Django 3.1 on 2022-08-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_bidhaa_stoku_full_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidhaa_stoku',
            name='full_Return',
        ),
        migrations.AddField(
            model_name='stokadjustment',
            name='full_Return',
            field=models.BooleanField(default=False),
        ),
    ]
