# Generated by Django 3.1 on 2022-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_auto_20220810_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjst_confirm',
            name='Return',
            field=models.BooleanField(default=False),
        ),
    ]
