# Generated by Django 3.1 on 2022-08-15 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_stockadjst_confirm_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnMauzo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarehe', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='mauzoni',
            name='ReturnMap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.returnmauzo'),
        ),
        migrations.AddField(
            model_name='sale_return',
            name='ReturnMap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.returnmauzo'),
        ),
    ]
