# Generated by Django 3.1 on 2022-08-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_auto_20220815_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mauzoni',
            name='ReturnMap',
        ),
        migrations.RemoveField(
            model_name='sale_return',
            name='ReturnMap',
        ),
        migrations.DeleteModel(
            name='ReturnMauzo',
        ),
    ]
