# Generated by Django 3.1 on 2022-08-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_auto_20220815_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedriport',
            name='SReturn',
            field=models.BooleanField(default=False),
        ),
    ]
