# Generated by Django 3.1 on 2022-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_savedriport_sreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedriport',
            name='serviceIncome',
            field=models.BooleanField(default=False),
        ),
    ]
