# Generated by Django 3.1 on 2022-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_savedriport_serviceincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='manunuzilist',
            name='before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='production_color',
            name='before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='production_size',
            name='before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productionlist',
            name='before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchased_color',
            name='before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchased_size',
            name='before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receivelist',
            name='before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
