# Generated by Django 3.1 on 2022-08-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_auto_20220826_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhaa_stoku',
            name='manunuzi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.manunuzilist'),
        ),
        migrations.AlterField(
            model_name='bidhaa_stoku',
            name='ongezwa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.stokadjustment'),
        ),
        migrations.AlterField(
            model_name='bidhaa_stoku',
            name='produced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.productionlist'),
        ),
    ]
