# Generated by Django 3.1 on 2022-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_auto_20220827_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='manunuzi',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manunuzi',
            name='markDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
