# Generated by Django 3.1 on 2022-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_auto_20220828_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='manunuzi',
            name='markTitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
