# Generated by Django 3.1 on 2022-09-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_manunuzi_marktitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='production',
            name='markDesc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202209),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202209),
        ),
    ]
