# Generated by Django 3.1 on 2022-09-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_auto_20220921_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='production',
            name='markDesc',
        ),
        migrations.AddField(
            model_name='productionconfirm',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionconfirm',
            name='markDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
