# Generated by Django 3.1 on 2022-09-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_auto_20220921_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionconfirm',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='productionconfirm',
            name='markDesc',
        ),
        migrations.AddField(
            model_name='productionlistdate',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productionlistdate',
            name='code_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionlistdate',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionlistdate',
            name='markDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
