# Generated by Django 3.1 on 2022-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_auto_20220921_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivelist',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receivelist',
            name='markDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
