# Generated by Django 3.1 on 2022-09-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_auto_20220922_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivelist',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='receivelist',
            name='markDesc',
        ),
        migrations.AddField(
            model_name='receive',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receive',
            name='markDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
