# Generated by Django 3.1 on 2022-09-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_auto_20220922_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokadjustment',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stokadjustment',
            name='markDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
