# Generated by Django 3.1 on 2022-10-05 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_auto_20221005_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='toacash',
            name='matumizi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.rekodimatumizi'),
        ),
    ]
