# Generated by Django 3.1 on 2022-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_toacash_matumizi'),
    ]

    operations = [
        migrations.AddField(
            model_name='toacash',
            name='kuhamisha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wekacash',
            name='kuhamisha',
            field=models.BooleanField(default=False),
        ),
    ]
