# Generated by Django 3.1 on 2022-10-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_auto_20221006_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentakaunts',
            name='owner',
        ),
    ]
