# Generated by Django 3.1 on 2022-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_remove_paymentakaunts_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wekacash',
            name='mtaji',
            field=models.BooleanField(default=False),
        ),
    ]
