# Generated by Django 3.1 on 2022-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_wekacash_mtaji'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentakaunts',
            name='addedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
