# Generated by Django 3.1 on 2022-10-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_paymentakaunts_addeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='toacash',
            name='kuhamishaNje',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toacash',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wekacash',
            name='kuhamishaNje',
            field=models.BooleanField(default=False),
        ),
    ]
