# Generated by Django 3.1 on 2022-10-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_auto_20221008_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='produxn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interprise',
            name='sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interprise',
            name='service',
            field=models.BooleanField(default=True),
        ),
    ]
