# Generated by Django 3.1 on 2022-11-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_auto_20221029_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idadi', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='bill_return_pu_fidia',
            name='re_am',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cash_order_return',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cash_order_return',
            name='makato',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pu_size_ret',
            name='idadi',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchased_size',
            name='before',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchased_size',
            name='idadi',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchased_size',
            name='rudi',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='ilolipwa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='kiasi',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sale_return_mauzo_fidia',
            name='re_am',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='After',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='Amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='before',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202211),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='After',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='Amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='before',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202211),
        ),
        migrations.CreateModel(
            name='SizeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idadi', models.DecimalField(decimal_places=4, max_digits=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.colorstate')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.produ_size')),
            ],
        ),
        migrations.CreateModel(
            name='savedStockState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maelezo', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprisepermissions')),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
            ],
        ),
        migrations.CreateModel(
            name='SaveAkauntState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiasi', models.DecimalField(decimal_places=4, max_digits=20)),
                ('akaunt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.paymentakaunts')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.savedstockstate')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idadi', models.DecimalField(decimal_places=4, max_digits=20)),
                ('bidhaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_stoku')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.savedstockstate')),
            ],
        ),
        migrations.AddField(
            model_name='colorstate',
            name='bidhaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.itemsstate'),
        ),
        migrations.AddField(
            model_name='colorstate',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.produ_colored'),
        ),
    ]
