# Generated by Django 3.1 on 2022-11-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_auto_20221108_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SizeState',
        ),
    ]
