# Generated by Django 3.1 on 2022-11-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_delete_sizestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idadi', models.DecimalField(decimal_places=4, max_digits=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.colorstate')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.produ_size')),
            ],
        ),
    ]
