# Generated by Django 3.1 on 2022-11-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_sizestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorstate',
            name='bidhaa',
        ),
        migrations.RemoveField(
            model_name='sizestate',
            name='color',
        ),
        migrations.AddField(
            model_name='colorstate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.savedstockstate'),
        ),
        migrations.AddField(
            model_name='sizestate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.savedstockstate'),
        ),
        migrations.AlterField(
            model_name='itemsstate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.savedstockstate'),
        ),
    ]
