# Generated by Django 3.1 on 2022-11-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_auto_20221108_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorstate',
            old_name='color',
            new_name='scolor',
        ),
        migrations.RenameField(
            model_name='colorstate',
            old_name='idadi',
            new_name='sidadi',
        ),
        migrations.RenameField(
            model_name='itemsstate',
            old_name='bidhaa',
            new_name='sbidhaa',
        ),
        migrations.RenameField(
            model_name='itemsstate',
            old_name='idadi',
            new_name='sidadi',
        ),
        migrations.RenameField(
            model_name='saveakauntstate',
            old_name='akaunt',
            new_name='sakaunt',
        ),
        migrations.RenameField(
            model_name='sizestate',
            old_name='idadi',
            new_name='sidadi',
        ),
        migrations.RenameField(
            model_name='sizestate',
            old_name='size',
            new_name='ssize',
        ),
    ]
