# Generated by Django 3.1 on 2022-11-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0070_auto_20221113_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedstockstate',
            name='By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprisepermissions'),
        ),
        migrations.CreateModel(
            name='InterpriseVisotrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('homePage', models.IntegerField(blank=True, null=True)),
                ('AboutPage', models.IntegerField(blank=True, null=True)),
                ('MapPage', models.IntegerField(blank=True, null=True)),
                ('RegPage', models.IntegerField(blank=True, null=True)),
                ('ipaddres', models.CharField(max_length=100)),
                ('BrandPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.makampuni')),
                ('CategoryPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_aina')),
                ('GroupPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.mahitaji')),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
                ('ItemPage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_stoku')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.userextend')),
            ],
        ),
    ]
