# Generated by Django 3.1 on 2022-11-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_auto_20221120_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisevisotrs',
            name='visted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interprisevisotrs',
            name='AboutPage',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='interprisevisotrs',
            name='MapPage',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='interprisevisotrs',
            name='RegPage',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='interprisevisotrs',
            name='homePage',
            field=models.IntegerField(default=False),
        ),
    ]
