# Generated by Django 3.1 on 2022-11-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0072_auto_20221120_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaa_stoku',
            name='visted',
            field=models.IntegerField(default=0),
        ),
    ]
