# Generated by Django 3.1 on 2022-11-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0073_bidhaa_stoku_visted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaa',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='ItemsAudio'),
        ),
        migrations.AddField(
            model_name='bidhaa_aina',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='ItemsAudio'),
        ),
        migrations.AddField(
            model_name='bidhaa_stoku',
            name='showToVistors',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mahitaji',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='ItemsAudio'),
        ),
        migrations.AddField(
            model_name='makampuni',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='ItemsAudio'),
        ),
    ]
