# Generated by Django 3.1 on 2022-11-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_auto_20221129_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistorsSavedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidhaa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_stoku')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.userextend')),
            ],
        ),
    ]
