# Generated by Django 3.1 on 2022-12-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0075_vistorssaveditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='onlineCustomers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202212),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202212),
        ),
        migrations.CreateModel(
            name='Interprise_Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('desc', models.TextField(blank=True, null=True)),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.userextend')),
            ],
        ),
    ]
