# Generated by Django 3.1 on 2022-12-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_auto_20221217_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise_rating',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
