# Generated by Django 3.1 on 2022-12-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_interprise_rating_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise_rating',
            name='invo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.mauzoni'),
        ),
    ]
