# Generated by Django 3.1 on 2022-12-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_interprise_rating_invo'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise_rating',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='interprise_rating',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
