# Generated by Django 3.1 on 2022-12-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0079_auto_20221222_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise_rating',
            name='repDate',
            field=models.DateTimeField(null=True),
        ),
    ]
