# Generated by Django 3.1 on 2023-01-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0080_interprise_rating_repdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mikoani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mkoa', models.CharField(max_length=80)),
                ('kanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.kanda')),
            ],
        ),
        migrations.CreateModel(
            name='Nchi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userextend',
            name='ImModelate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='ImSuper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202301),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202301),
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=80)),
                ('mkoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.mikoani')),
            ],
        ),
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata', models.CharField(max_length=80)),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.wilaya')),
            ],
        ),
        migrations.AddField(
            model_name='kanda',
            name='nchi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.nchi'),
        ),
        migrations.AddField(
            model_name='userextend',
            name='kata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.kata'),
        ),
    ]
