# Generated by Django 3.1 on 2023-01-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0081_auto_20230111_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanda',
            name='nchi',
        ),
        migrations.RenameModel(
            old_name='Mikoani',
            new_name='Mikoa',
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanda', models.CharField(max_length=70)),
                ('nchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.nchi')),
            ],
        ),
        migrations.AlterField(
            model_name='mikoa',
            name='kanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.zones'),
        ),
    ]
