# Generated by Django 3.1 on 2023-01-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0082_auto_20230111_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interprise',
            name='mtaa',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='kata',
        ),
        migrations.CreateModel(
            name='Mtaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kijiji', models.CharField(max_length=80)),
                ('kata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.kata')),
            ],
        ),
        migrations.AddField(
            model_name='userextend',
            name='mtaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.mtaa'),
        ),
    ]
