# Generated by Django 3.1 on 2023-01-18 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0083_auto_20230118_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='mtaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.mtaa'),
        ),
    ]
