# Generated by Django 3.1 on 2023-01-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0084_interprise_mtaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.wilaya'),
        ),
        migrations.AlterField(
            model_name='mikoa',
            name='kanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.zones'),
        ),
        migrations.AlterField(
            model_name='mtaa',
            name='kata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.kata'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='mkoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.mikoa'),
        ),
    ]
