# Generated by Django 3.1 on 2023-01-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0085_auto_20230118_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mtaa',
            new_name='Mitaa',
        ),
    ]
