# Generated by Django 3.1 on 2023-01-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0086_auto_20230118_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitaa',
            old_name='kijiji',
            new_name='mtaa',
        ),
    ]
