# Generated by Django 3.1 on 2023-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0087_auto_20230118_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneMailConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneMail', models.CharField(max_length=100)),
                ('confirm', models.BooleanField(default=False)),
                ('code', models.IntegerField()),
                ('duration', models.DateTimeField()),
            ],
        ),
    ]
