# Generated by Django 3.1 on 2023-01-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0088_phonemailconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='gender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
