# Generated by Django 3.1 on 2023-01-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0089_userextend_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='nchi',
            name='currencii',
            field=models.CharField(default='TZS', max_length=10),
            preserve_default=False,
        ),
    ]
