# Generated by Django 3.1 on 2023-01-26 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0090_nchi_currencii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interprise',
            name='kanda',
        ),
        migrations.RemoveField(
            model_name='interprise',
            name='mkoa',
        ),
        migrations.RemoveField(
            model_name='interprise',
            name='wilaya',
        ),
    ]
