# Generated by Django 3.1 on 2023-01-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0091_auto_20230126_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interprise',
            name='country',
        ),
    ]
