# Generated by Django 3.1 on 2023-01-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0092_remove_interprise_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='simu1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
