# Generated by Django 3.1 on 2023-02-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0094_auto_20230201_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhaa',
            name='Asize',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bidhaa_aina',
            name='Asize',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mahitaji',
            name='Asize',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='makampuni',
            name='Asize',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
