# Generated by Django 3.1 on 2023-02-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0095_auto_20230201_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='business',
            field=models.IntegerField(default=0),
        ),
    ]
