# Generated by Django 3.1 on 2023-02-08 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0096_userextend_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='Balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='KulipaPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('Interprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprise')),
            ],
        ),
    ]
