# Generated by Django 3.1 on 2023-02-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0097_auto_20230208_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='company',
            field=models.BooleanField(default=False),
        ),
    ]
