# Generated by Django 3.1 on 2023-02-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0098_userextend_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='marketing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interprise',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
