# Generated by Django 3.1 on 2023-02-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0099_auto_20230209_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='bill_tobePaid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
