# Generated by Django 3.1 on 2023-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0100_interprise_bill_tobepaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interprise',
            name='bill_tobePaid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
