# Generated by Django 3.1 on 2023-02-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0101_auto_20230210_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='marketBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('vistors', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('visted', models.IntegerField(default=0)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='marketPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.marketbanner')),
                ('mkoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.mikoa')),
                ('nchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.nchi')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.wilaya')),
            ],
        ),
    ]
