# Generated by Django 3.1 on 2023-02-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0102_marketbanner_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbanner',
            name='Interprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprise'),
        ),
    ]
