# Generated by Django 3.1 on 2023-02-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0103_marketbanner_interprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbanner',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketbanner',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
