# Generated by Django 3.1 on 2023-02-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0104_auto_20230215_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbanner',
            name='aina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_aina'),
        ),
        migrations.AddField(
            model_name='marketbanner',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.makampuni'),
        ),
        migrations.AddField(
            model_name='marketbanner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.mahitaji'),
        ),
        migrations.AddField(
            model_name='marketbanner',
            name='itm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_stoku'),
        ),
    ]
