# Generated by Django 3.1 on 2023-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0105_auto_20230217_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interprise',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
