# Generated by Django 3.1 on 2023-02-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0106_auto_20230219_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='vistedPosts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
