# Generated by Django 3.1 on 2023-02-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0107_userextend_vistedposts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ainaBibi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ainaMama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jina', models.CharField(max_length=100)),
                ('aina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.ainabibi')),
            ],
        ),
        migrations.AddField(
            model_name='mahitaji',
            name='aina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.ainamama'),
        ),
    ]
