# Generated by Django 3.1 on 2023-02-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0108_auto_20230223_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahitaji',
            old_name='aina',
            new_name='aina_g',
        ),
    ]
