# Generated by Django 3.1 on 2023-02-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0109_auto_20230224_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahitaji',
            old_name='aina_g',
            new_name='aina',
        ),
    ]
