# Generated by Django 3.1 on 2023-03-03 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0110_auto_20230224_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202303),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202303),
        ),
        migrations.CreateModel(
            name='VistorsSavedVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.ainamama')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.userextend')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
            ],
        ),
    ]
