# Generated by Django 3.1 on 2023-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0111_auto_20230303_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vistorssavedvendor',
            name='aina',
        ),
        migrations.AddField(
            model_name='vistorssavedvendor',
            name='desk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
