# Generated by Django 3.1 on 2023-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0112_auto_20230304_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='slogan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
