# Generated by Django 3.1 on 2023-03-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0113_interprise_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaa',
            name='colorAttr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
