# Generated by Django 3.1 on 2023-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0114_bidhaa_colorattr'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryby',
            name='amehakiki',
            field=models.BooleanField(default=True),
        ),
    ]
