# Generated by Django 3.1 on 2023-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0115_deliveryby_amehakiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryby',
            name='seen',
            field=models.BooleanField(default=True),
        ),
    ]
