# Generated by Django 3.1 on 2023-03-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0116_deliveryby_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryby',
            name='Invo_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliveryby',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
