# Generated by Django 3.1 on 2023-03-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0117_auto_20230311_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryby',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.deliveryagents'),
        ),
    ]
