# Generated by Django 3.1 on 2023-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0118_deliveryby_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryby',
            name='fromOrdered',
            field=models.BooleanField(default=True),
        ),
    ]
