# Generated by Django 3.1 on 2023-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0119_deliveryby_fromordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryby',
            name='aliyekabidhiwa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryby',
            name='amehakiki',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryby',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
