# Generated by Django 3.1 on 2023-03-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0120_auto_20230312_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='pickups',
            field=models.BooleanField(default=False),
        ),
    ]
