# Generated by Django 3.1 on 2023-03-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0121_chats_pickups'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='pickUp',
            field=models.BooleanField(default=False),
        ),
    ]
