# Generated by Django 3.1 on 2023-03-25 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0122_notifications_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistedBanners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.marketbanner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.userextend')),
            ],
        ),
    ]
