# Generated by Django 3.1 on 2023-03-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0123_vistedbanners'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbanner',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.userextend'),
        ),
    ]
