# Generated by Django 3.1 on 2023-04-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0124_marketbanner_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='pwdResets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202304),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202304),
        ),
    ]
