# Generated by Django 4.2 on 2023-08-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0126_interprise_created_alter_ainabibi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='desc_Pro_To',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202308),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202308),
        ),
    ]
