# Generated by Django 4.2 on 2023-08-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0127_interprise_desc_pro_to_alter_toacash_monthcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('Interprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
            ],
        ),
    ]
