# Generated by Django 4.2 on 2023-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0128_descimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descimages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
