# Generated by Django 4.2 on 2023-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0129_alter_descimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='descimages',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
        migrations.AlterField(
            model_name='descimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
