# Generated by Django 4.2 on 2023-08-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0130_descimages_attach_alter_descimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descimages',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='sharedFolder'),
        ),
        migrations.AlterField(
            model_name='descimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sharedFolder'),
        ),
    ]
