# Generated by Django 4.1.1 on 2023-09-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0131_alter_descimages_attach_alter_descimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202309),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202309),
        ),
        migrations.CreateModel(
            name='Activator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.userextend')),
            ],
        ),
        migrations.CreateModel(
            name='Activated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.activator')),
                ('activatd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.userextend')),
            ],
        ),
    ]
