# Generated by Django 4.1.1 on 2023-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0132_alter_toacash_monthcode_alter_wekacash_monthcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activator',
            name='lastpaid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
