# Generated by Django 4.1.1 on 2024-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0133_activator_lastpaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='monthcode',
            field=models.IntegerField(default=202404),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='monthcode',
            field=models.IntegerField(default=202404),
        ),
    ]
