# Generated by Django 5.0.7 on 2024-09-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0134_userextend_darkmode_alter_toacash_monthcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toacash',
            name='monthcode',
        ),
        migrations.RemoveField(
            model_name='wekacash',
            name='monthcode',
        ),
    ]
