# Generated by Django 5.0.7 on 2024-10-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0135_remove_toacash_monthcode_remove_wekacash_monthcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('date', models.DateTimeField()),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
            ],
        ),
    ]
