# Generated by Django 5.0.7 on 2024-10-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0136_invoice_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='invo_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.invoice_desk'),
        ),
    ]
