# Generated by Django 5.0.7 on 2024-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0137_mauzoni_invo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='mnRecipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interprisepermissions',
            name='receiptSet',
            field=models.BooleanField(default=False),
        ),
    ]
