# Generated by Django 5.0.7 on 2024-10-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0138_interprisepermissions_mnrecipt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
            ],
        ),
        migrations.CreateModel(
            name='customer_in_cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customer_area')),
            ],
        ),
        migrations.AddField(
            model_name='mauzoni',
            name='customer_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.customer_in_cell'),
        ),
    ]
