# Generated by Django 5.0.7 on 2024-11-07 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0139_customer_area_customer_in_cell_mauzoni_customer_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForPrintingPupose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire', models.DateTimeField()),
                ('ipaddre', models.TextField()),
                ('mauzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.mauzoni')),
                ('purch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.manunuzi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.userextend')),
            ],
        ),
    ]
