# Generated by Django 5.0.7 on 2024-11-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0140_forprintingpupose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forprintingpupose',
            name='mauzo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.mauzoni'),
        ),
        migrations.AlterField(
            model_name='forprintingpupose',
            name='purch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.manunuzi'),
        ),
    ]
