# Generated by Django 5.0.7 on 2024-11-07 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0141_alter_forprintingpupose_mauzo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forprintingpupose',
            name='purch',
        ),
    ]
