# Generated by Django 5.0.7 on 2024-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0142_remove_forprintingpupose_purch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forprintingpupose',
            name='ipaddre',
            field=models.CharField(max_length=100),
        ),
    ]
