# Generated by Django 5.0.7 on 2024-11-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0143_alter_forprintingpupose_ipaddre'),
    ]

    operations = [
        migrations.AddField(
            model_name='forprintingpupose',
            name='duka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprise'),
        ),
    ]
