# Generated by Django 5.0.7 on 2025-03-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0144_forprintingpupose_duka'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='officeNo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
