# Generated by Django 5.0.7 on 2025-03-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0145_interprise_officeno'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='showNum1',
            field=models.BooleanField(default=True),
        ),
    ]
