# Generated by Django 6.0.1 on 2026-04-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0146_userextend_shownum1'),
    ]

    operations = [
        migrations.AddField(
            model_name='picha_yenyewe',
            name='picha_hash',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
