# Generated by Django 6.0.1 on 2026-04-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0147_picha_yenyewe_picha_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picha_yenyewe',
            name='picha_hash',
            field=models.CharField(blank=True, db_index=True, max_length=600, null=True),
        ),
    ]
