# Generated by Django 6.0.1 on 2026-05-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0148_alter_picha_yenyewe_picha_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='waiter_counter',
            field=models.BooleanField(default=False),
        ),
    ]
