# Generated by Django 6.0.1 on 2026-05-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0150_interprisepermissions_waiter_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='servicing',
            field=models.BooleanField(default=False),
        ),
    ]
