# Generated by Django 6.0.1 on 2026-05-04 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0151_interprisepermissions_servicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='waiter_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_orders', to='management.interprisepermissions'),
        ),
    ]
