# Generated by Django 6.0.1 on 2026-05-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0152_mauzoni_waiter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='waiter_pay',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
