# Generated by Django 6.0.1 on 2026-05-05 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0153_mauzoni_waiter_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='waiterMobilePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tarehe', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.paymentakaunts')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.mauzoni')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.interprisepermissions')),
            ],
        ),
    ]
