# Generated by Django 6.0.1 on 2026-05-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0154_waitermobilepay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='waiterMobilePay',
            new_name='waiterPayments',
        ),
    ]
