# Generated by Django 6.0.1 on 2026-05-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0155_rename_waitermobilepay_waiterpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterpayments',
            name='customerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
