# Generated by Django 6.0.1 on 2026-05-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0156_waiterpayments_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='waiter_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
