# Generated by Django 6.0.1 on 2026-05-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0157_interprisepermissions_waiter_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mauzoni',
            name='printed_number',
            field=models.IntegerField(default=0),
        ),
    ]
