# Generated by Django 6.0.1 on 2026-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0158_mauzoni_printed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='enable_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interprisepermissions',
            name='waiter_pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
