# Generated by Django 6.0.1 on 2026-05-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0159_interprisepermissions_enable_print_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterPosDeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
            ],
            options={
                'unique_together': {('Interprise', 'device_id')},
            },
        ),
    ]
