# Generated by Django 6.0.1 on 2026-05-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0160_waiterposdevicesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterposdevicesession',
            name='active_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprisepermissions'),
        ),
    ]
