# Generated by Django 6.0.1 on 2026-05-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0161_waiterposdevicesession_active_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterposdevicesession',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
