# Generated by Django 6.0.1 on 2026-05-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0162_waiterposdevicesession_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='waiter_check_up',
            field=models.BooleanField(default=False),
        ),
    ]
