# Generated by Django 6.0.1 on 2026-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0163_interprisepermissions_waiter_check_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='waiter_delete_order',
            field=models.BooleanField(default=False),
        ),
    ]
