# Generated by Django 6.0.1 on 2026-05-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0164_interprisepermissions_waiter_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='waiter_clearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('tarehe', models.DateTimeField()),
                ('By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_clearing_by_set', to='management.interprisepermissions')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiter_clearing_waiter_set', to='management.interprisepermissions')),
            ],
        ),
        migrations.AddField(
            model_name='mauzoni',
            name='waiter_order_cleared',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.waiter_clearing'),
        ),
        migrations.AddField(
            model_name='wekacash',
            name='from_waiter_payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.waiter_clearing'),
        ),
    ]
