# Generated by Django 6.0.1 on 2026-05-09 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0165_waiter_clearing_mauzoni_waiter_order_cleared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='cash_deposit_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentakaunts',
            name='supervisor_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toacash',
            name='supervisor_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_deposit_set', to='management.interprisepermissions'),
        ),
    ]
