# Generated by Django 6.0.1 on 2026-05-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0166_interprisepermissions_cash_deposit_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toacash',
            name='deposit_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_to_set', to='management.wekacash'),
        ),
    ]
