# Generated by Django 6.0.1 on 2026-05-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0167_toacash_deposit_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='cash_deposit_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toacash',
            name='admin_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wekacash',
            name='admin_approve',
            field=models.BooleanField(default=False),
        ),
    ]
