# Generated by Django 6.0.1 on 2026-05-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0168_interprisepermissions_cash_deposit_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='shift_management_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShiftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('shift_type', models.CharField(default='daily', max_length=20)),
                ('status', models.CharField(default='open', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('expected_closing_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('actual_closing_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('variance', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shift_set', to='management.interprisepermissions')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_shift_set', to='management.interprisepermissions')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shift_set', to='management.interprisepermissions')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='recorder', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_assigner_set', to='management.interprisepermissions')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprisepermissions')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.shiftsession')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('event_ref_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprisepermissions')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.shiftsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='shiftsession',
            index=models.Index(fields=['Interprise', 'status'], name='management__Interpr_c37bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftsession',
            index=models.Index(fields=['starts_at', 'ends_at'], name='management__starts__bd5a41_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift', 'active'], name='management__shift_i_59aec0_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['staff', 'active'], name='management__staff_i_cff41b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('shift', 'staff', 'role')},
        ),
        migrations.AddIndex(
            model_name='shiftactivity',
            index=models.Index(fields=['shift', 'event_type'], name='management__shift_i_0291dc_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftactivity',
            index=models.Index(fields=['recorded_at'], name='management__recorde_6167f3_idx'),
        ),
    ]
