# Generated by Django 6.0.1 on 2026-05-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0169_interprise_shift_management_enabled_shiftsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='add_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interprisepermissions',
            name='staff_management',
            field=models.BooleanField(default=False),
        ),
    ]
