# Generated by Django 6.0.1 on 2026-05-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0170_interprisepermissions_add_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='close_own_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interprisepermissions',
            name='open_own_shift',
            field=models.BooleanField(default=False),
        ),
    ]
