# Generated by Django 6.0.1 on 2026-05-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0171_interprisepermissions_close_own_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidhaa_stoku',
            name='is_grouped_item',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='grouped_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('Bei_kununua', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('Bei_kuuza', models.DecimalField(decimal_places=4, max_digits=15)),
                ('idadi', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
            ],
            options={
                'verbose_name_plural': 'grouped_items',
            },
        ),
        migrations.AddField(
            model_name='bidhaa_stoku',
            name='grouped_item_ref',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.grouped_item'),
        ),
        migrations.CreateModel(
            name='grouped_item_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidhaa_stoku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_stoku')),
                ('grouped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='management.grouped_item')),
            ],
            options={
                'unique_together': {('grouped', 'bidhaa_stoku')},
            },
        ),
        migrations.CreateModel(
            name='grouped_item_reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recorded_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('Interprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.interprise')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.interprisepermissions')),
                ('grouped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.grouped_item')),
            ],
            options={
                'unique_together': {('grouped', 'Interprise', 'date')},
            },
        ),
    ]
