# Generated by Django 6.0.1 on 2026-05-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0173_bidhaa_stoku_grouped_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidhaa_stoku',
            name='grouped_item_qty_sold',
        ),
    ]
