# Generated by Django 6.0.1 on 2026-06-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0174_remove_bidhaa_stoku_grouped_item_qty_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='dashboard_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
