# Generated by Django 6.0.1 on 2026-06-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0175_interprisepermissions_dashboard_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidhaa',
            name='bidhaa_aina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.bidhaa_aina'),
        ),
        migrations.AlterField(
            model_name='bidhaa',
            name='kampuni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.makampuni'),
        ),
    ]
