# Generated by Django 6.0.1 on 2026-08-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0181_workers_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_interprise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
