# Generated by Django 6.0.1 on 2026-10-02 12:04

import django.db.models.deletion
from django.db import migrations, models


def mark_existing_purchases_approved(apps, schema_editor):
    manunuzi = apps.get_model('management', 'manunuzi')
    manunuzi.objects.update(admin_approved=True)
    wekaCash = apps.get_model('management', 'wekaCash')
    wekaCash.objects.update(admin_approve=True)


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0189_manunuzi_admin_approved_manunuzi_admin_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprise',
            name='require_purchase_payment_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizireceiptattachment',
            name='toa_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_attachments', to='management.toacash'),
        ),
        migrations.AddField(
            model_name='receive',
            name='admin_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receive',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receive',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receives_approved', to='management.interprisepermissions'),
        ),
        migrations.RunPython(mark_existing_purchases_approved, migrations.RunPython.noop),
    ]
